apiVersion: apps/v1
kind: Deployment
metadata:
  name: student13-deployment
spec:
  selector:
    matchLabels:
      app: student13
  template:
    metadata:
      labels:
        app: student13
    spec:
      containers:
      - name: student13
        image: registry.tanzu.dk/ops2devops/student13:v1
